#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
URL=https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip
FILENAME=terraform_${VERSION}_linux_amd64.zip

curl -L -o /tmp/${FILENAME} $URL
cd /tmp
unzip ${FILENAME}
rm ${FILENAME}

mv -f /tmp/terraform /usr/local/bin/.
chown root:root /usr/local/bin/terraform