#!/usr/bin/env bash

if protoc --version &> /dev/null
then
    go get -u google.golang.org/protobuf/cmd/protoc-gen-go
    go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
    go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
fi
