#!/usr/bin/env bash

go install golang.org/x/lint/golint@latest
go install github.com/daixiang0/gci@latest
go install mvdan.cc/gofumpt@latest
go install github.com/swaggo/swag/cmd/swag@latest
go install github.com/sonatype-nexus-community/nancy@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# VERSION=$(github-latest golangci/golangci-lint)
# curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$VERSION
