#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

#curl -L https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz | tar zx -C /tmp
curl -L https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz.zip -o /tmp/starship-x86_64-unknown-linux-gnu.tar.gz.zip
cd /tmp
unzip -q starship-x86_64-unknown-linux-gnu.tar.gz.zip
rm -f /tmp/starship-x86_64-unknown-linux-gnu.tar.gz.zip
cd starship-x86_64-unknown-linux-gnu.tar.gz
tar zxf starship-x86_64-unknown-linux-gnu.tar.gz
rm -f starship-x86_64-unknown-linux-gnu.tar.gz
mv starship /usr/local/bin/starship
chown root:root /usr/local/bin/starship
cd --
rmdir /tmp/starship-x86_64-unknown-linux-gnu.tar.gz