#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

VERSION=$(github-latest gohugoio/hugo)
curl -L https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz | tar zx -C /tmp
install -o root -g root /tmp/hugo /usr/local/bin


