#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

curl -L https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz | tar zx -C /tmp
mv /tmp/starship /usr/local/bin.
chown root:root /usr/local/bin/starship