#!/usr/bin/env bash

go install github.com/kubernetes/code-generator/cmd/defaulter-gen@latest
go install github.com/kubernetes/code-generator/cmd/client-gen@latest
go install github.com/kubernetes/code-generator/cmd/lister-gen@latest
go install github.com/kubernetes/code-generator/cmd/informer-gen@latest
go install github.com/kubernetes/code-generator/cmd/deepcopy-gen@latest
