#!/usr/bin/env bash

URL="https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_darwin_amd64.zip"

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

curl -L -o /usr/local/bin/terraform $URL
chmod 755 /usr/local/bin/terraform