#!/usr/bin/env bash

go get -u golang.org/x/lint/golint
go get -u github.com/daixiang0/gci

VERSION=$(github-latest golangci/golangci-lint)
go get github.com/golangci/golangci-lint/cmd/golangci-lint@v$VERSION
