#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

VERSION=$(github-latest helm/helm 3)
curl -L https://get.helm.sh/helm-v${VERSION}-linux-amd64.tar.gz | tar zx -C /tmp
install -o root -g root /tmp/linux-amd64/helm /usr/local/bin
rm -fr /tmp/linux-amd64
