#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

url="$(curl -sS https://go.dev/dl/ | grep -oP '\/dl\/go([0-9\.]+)\.linux-amd64\.tar\.gz' | head -n 1 )"
latest="$(echo $url | grep -oP 'go[0-9\.]+' | grep -oP '[0-9\.]+' | head -c -2 )"

rm -rf /usr/local/go
curl -L "https://go.dev/dl/go${latest}.linux-amd64.tar.gz" | tar -zxC /usr/local
