#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
URL=https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip
FILENAME=terraform_${VERSION}_linux_amd64.zip

cd /tmp
curl -L -o ${FILENAME} $URL
unzip -d /usr/local/bin -o ${FILENAME}
rm ${FILENAME}
chown root:root /usr/local/bin/terraform
